[package]
name = 'utils'
version = '1.0.0'

[addresses]
utils = "_"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'devnet'
subdir = 'aptos-move/framework/aptos-framework'
